[filter "gemini-theme"]
  clean = sed -E 's/^([[:space:]]*\"theme\")[[:space:]]*:.*$/\\1: \"Default Light\"/'
  smudge = cat

[filter "yazi-theme"]
  clean = sed -E 's/^(dark|light)[[:space:]]*=.*$/\\1 = \"catppuccin-latte\"/'
  smudge = cat

[filter "btop-theme"]
  clean = sed -E 's/^(color_theme[[:space:]]*=[[:space:]]*\").*\"$/\\1catppuccin_latte\"/'
  smudge = cat

[filter "patina-theme"]
  clean = sed -E 's/^([[:space:]]*theme[[:space:]]*=[[:space:]]*).*$/\\1\"classic\"/'
  smudge = cat

[filter "ipython-theme"]
  clean = sed -E \"s/^[[:space:]]*c\\.InteractiveShell\\.colors[[:space:]]*=.*$/c.InteractiveShell.colors = 'lightbg'/\" | sed -E \"s/^[[:space:]]*c\\.TerminalInteractiveShell\\.colors[[:space:]]*=.*$/c.TerminalInteractiveShell.colors = 'lightbg'/\"
  smudge = cat
