[filter "gemini-theme"]
  clean = sed -E 's/^([[:space:]]*\"theme\")[[:space:]]*:[^,]*(,?)$/\\1: \"Default Light\"/'
  smudge = cat

[filter "claude-theme"]
  clean = sed -E 's/^([[:space:]]*\"theme\")[[:space:]]*:[^,]*(,?)$/\\1: \"light-ansi\"\\2/'
  smudge = cat

[filter "yazi-theme"]
  clean = sed -E 's/^(dark|light)[[:space:]]*=.*$/\\1 = \"catppuccin-latte\"/'
  smudge = cat

[filter "btop-theme"]
  clean = sed -E 's/^(color_theme[[:space:]]*=[[:space:]]*\").*\"$/\\1catppuccin_latte\"/'
  smudge = cat

[filter "patina-theme"]
  clean = sed -E 's/^([[:space:]]*theme[[:space:]]*=[[:space:]]*).*$/\\1\"classic\"/'
  smudge = cat

[filter "ipython-theme"]
  clean = sed -E \"s/^[[:space:]]*c\\.InteractiveShell\\.colors[[:space:]]*=.*$/c.InteractiveShell.colors = 'lightbg'/\" | sed -E \"s/^[[:space:]]*c\\.TerminalInteractiveShell\\.colors[[:space:]]*=.*$/c.TerminalInteractiveShell.colors = 'lightbg'/\"
  smudge = cat

[filter "typingmind_mcp"]
  clean = "sed -E '/<key>MCP_AUTH_TOKEN<\\/key>/ { N; s#(<key>MCP_AUTH_TOKEN</key>[[:space:]]*<string>)[^<]*(</string>)#\\1SECRET_PASSWORD\\2#; }'"
  smudge = cat

[filter "sublime-merge-draw-white-space"]
  clean = sed -E 's/^([[:space:]]*\"draw_white_space\")[[:space:]]*:[^,]*(,?)$/\\1: \"all\"\\2/'
  smudge = cat

[filter "sublime-merge-ignore-diff-white-space"]
  clean = sed -E 's/^([[:space:]]*\"ignore_diff_white_space\")[[:space:]]*:[^,]*(,?)$/\\1: false\\2/'
  smudge = cat